// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB_xhPLH8vVLearcKE5VFHElZtvwzHMrQ',
    appId: '1:838963325180:web:3da136d5d7d021e1aecf79',
    messagingSenderId: '838963325180',
    projectId: 'media-archive-b78c2',
    authDomain: 'media-archive-b78c2.firebaseapp.com',
    storageBucket: 'media-archive-b78c2.firebasestorage.app',
    measurementId: 'G-LWCVV8XMY8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO6gz1QI3fFgtumHi3WnhRwnI0f_t2dHo',
    appId: '1:838963325180:android:1f691b1e917bc887aecf79',
    messagingSenderId: '838963325180',
    projectId: 'media-archive-b78c2',
    storageBucket: 'media-archive-b78c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIPU_otBYApQBQKt8TnvsWItiWjPgLSTU',
    appId: '1:838963325180:ios:52239094297940ebaecf79',
    messagingSenderId: '838963325180',
    projectId: 'media-archive-b78c2',
    storageBucket: 'media-archive-b78c2.firebasestorage.app',
    iosBundleId: 'com.example.mediaArchive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIPU_otBYApQBQKt8TnvsWItiWjPgLSTU',
    appId: '1:838963325180:ios:52239094297940ebaecf79',
    messagingSenderId: '838963325180',
    projectId: 'media-archive-b78c2',
    storageBucket: 'media-archive-b78c2.firebasestorage.app',
    iosBundleId: 'com.example.mediaArchive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAB_xhPLH8vVLearcKE5VFHElZtvwzHMrQ',
    appId: '1:838963325180:web:74cb3edc8622a41baecf79',
    messagingSenderId: '838963325180',
    projectId: 'media-archive-b78c2',
    authDomain: 'media-archive-b78c2.firebaseapp.com',
    storageBucket: 'media-archive-b78c2.firebasestorage.app',
    measurementId: 'G-EYR9T9B3FP',
  );
}
